export const en = {
    // General
    titulo: 'Automatically Generated Documentation',
    autor: 'Generated by Albertool DocGen',
    
    // README
    readme_titulo: '📖 Project README',
    readme_descricao: 'Project description automatically generated',
    
    // ROUTES
    rotas_titulo: '🌐 API Routes',
    rotas_metodo: 'Method',
    rotas_rota: 'Route',
    rotas_descricao: 'Description',
    
    // SECURITY
    security_titulo: '🔒 Security',
    security_dependencias: 'Security dependencies',
    
    // ENV
    env_titulo: '🔧 Environment Variables',
    env_variavel: 'Variable',
    env_descricao: 'Description',
    
    // CHANGELOG
    changelog_titulo: '📋 Changelog',
    changelog_sem_commits: 'No commits found',
    
    // Controllers
    controllers_titulo: '📋 Controllers',
    controllers_sem: 'No controllers found',
    
    // Services
    services_titulo: '📋 Services',
    services_sem: 'No services found',
    
    // Models
    models_titulo: '📦 Models',
    models_sem: 'No models found',
    models_campo: 'Field',
    models_tipo: 'Type',
    
    // Repositories
    repositories_titulo: '🗄️ Repositories',
    repositories_sem: 'No repositories found',
    repositories_entidade: 'Entity',
    
    // Middlewares
    middlewares_titulo: '🛡️ Middlewares',
    middlewares_sem: 'No middlewares found',
    
    // Schemas
    schemas_titulo: '📝 Schemas (Zod)',
    schemas_sem: 'No schemas found',
    schemas_campo: 'Field',
    schemas_tipo: 'Type',
    schemas_validacao: 'Validation',
    
    // Misc
    misc_titulo: '📁 Misc Files',
    misc_sem: 'No misc files found'
};